OPTIONS = {
    "project": {"long": "--project", "short": "-P"},
    "status": {"long": "--status", "short": "-s"},
    "tracker": {"long": "--tracker", "short": "-t"},
    "priority": {"long": "--priority", "short": "-p"},
    "version": {"long": "--version", "short": "-v"},
    "assignee": {"long": "--assignee", "short": "-a"},
    "query": {"long": "--query", "short": "-q"},
    "subject": {"long": "--subject", "short": "-S"},
    "description": {"long": "--description", "short": "-D"},
    "note": {"long": "--note", "short": "-n"},
    "start": {"long": "--start", "short": "-b"},
    "due": {"long": "--due", "short": "-d"},
    "updated-on": {"long": "--updated-on"},
    "updated-after": {"long": "--updated-after"},
    "updated-before": {"long": "--updated-before"},
    "created-on": {"long": "--created-on"},
    "created-after": {"long": "--created-after"},
    "created-before": {"long": "--created-before"},
    "done": {"long": "--done", "short": "-f"},
    "parent": {"long": "--parent", "short": "-m"},
    "limit": {"long": "--limit", "short": "-l"},
    "sort": {"long": "--sort", "short": "-x"},
    "journals": {"long": "--journals/--no-journals", "short": "-j/-J"},
    "edit": {"long": "--edit/--no-edit", "short": "-e/-E"},
    "force": {"long": "--force/--no-force", "help": "Invalidate cache"},
    "json": {"long": "--json/--no-json"},
    "account": {"long": "--account"},
}
